### ISSUE TITLE
Bmo is awesome! :D

### ISSUE THREAD

**Issue by max107** [antoinelyset/bmo#1]
![687474703a2f2f696d61676573312e77696b69612e6e6f636f6f6b69652e6e65742f5f5f636232303133303631313230353134352f616476656e7475726574696d657769746866696e6e616e646a616b652f696d616765732f372f37302f4265656d6f2d64616e63696e672d6769662e676966](https://f.cloud.github.com/assets/862272/1860984/9500e04e-77bb-11e3-8979-1fcd656a6fac.gif)

**Comment by antoinelyset** [comment]
Haha yes !

![tumblr_mz0gmm3fgm1sciteso1_500](https://f.cloud.github.com/assets/1465371/1866830/fe959986-783e-11e3-8dc9-33f0d9ade6ad.gif)
